name: Build and Push to ACR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login to ACR
        run: az acr login --name acrterraform

      - name: Build and Push to ACR
        run: |
          # 1. Build da imagem
          docker build -t acrterraform.azurecr.io/acrterraform:${{ github.sha }} .
          
          # 2. Criar uma cópia da imagem com o nome 'latest'
          docker tag acrterraform.azurecr.io/acrterraform:${{ github.sha }} acrterraform.azurecr.io/acrterraform:latest
          
          # 3. Enviar as DUAS etiquetas para a Azure
          docker push acrterraform.azurecr.io/acrterraform:${{ github.sha }}
          docker push acrterraform.azurecr.io/acrterraform:latest